"""
note.py

Core memory abstraction for PRIMA (Persistent Agentic Memory).

This module defines the MemoryNote class, which represents an atomic,
self-contained unit of memory inspired by A-MEM (Agentic Memory).

Design principles:
- Atomic: one memory = one coherent experience
- Persistent: serializable for long-term storage
- Agentic: supports evolution, linking, and usage tracking
- Extensible: compatible with future memory research (forgetting, strength, planning)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional


def _now_ts() -> str:
    """Return current timestamp in YYYYMMDDHHMM format."""
    return datetime.now().strftime("%Y%m%d%H%M")


class MemoryNote:
    """
    Atomic memory unit in PRIMA.

    A MemoryNote represents a single piece of experience or knowledge
    stored by an agent. Notes are enriched with semantic metadata,
    connected via links, and can evolve over time.

    Conceptual mapping to A-MEM:
    - content   -> c_i (raw interaction)
    - timestamp -> t_i
    - keywords  -> K_i
    - tags      -> G_i
    - context   -> X_i
    - embedding -> e_i
    - links     -> L_i
    """

    # ----------------------------
    # Construction
    # ----------------------------

    def __init__(
        self,
        content: str,
        note_id: Optional[str] = None,
        timestamp: Optional[str] = None,
        # Semantic (LLM-generated)
        context: Optional[str] = None,
        keywords: Optional[List[str]] = None,
        tags: Optional[List[str]] = None,
        # Vector representation
        embedding: Optional[List[float]] = None,
        # Relational structure
        links: Optional[Dict[str, Dict[str, Any]]] = None,
        # Usage & evolution
        retrieval_count: int = 0,
        last_accessed: Optional[str] = None,
        evolution_history: Optional[List[Dict[str, Any]]] = None,
    ):
        """
        Initialize a MemoryNote.

        Args:
            content (str):
                Raw textual content of the memory (immutable after creation).
            note_id (Optional[str]):
                Unique identifier. If None, a UUID4 is generated.
            timestamp (Optional[str]):
                Creation time in YYYYMMDDHHMM format.
            context (Optional[str]):
                Abstract semantic summary generated by the LLM.
            keywords (Optional[List[str]]):
                Salient keywords extracted from the content.
            tags (Optional[List[str]]):
                High-level categorical tags.
            embedding (Optional[List[float]]):
                Dense vector representation for similarity search.
            links (Optional[Dict[str, Dict]]):
                Relationships to other memory notes.
                Format: {note_id: {metadata}}
            retrieval_count (int):
                Number of times this note has been retrieved.
            last_accessed (Optional[str]):
                Last retrieval timestamp.
            evolution_history (Optional[List[Dict]]):
                Audit trail of semantic evolution actions.
        """

        # ---- Identity (immutable) ----
        self.id: str = note_id or str(uuid.uuid4())
        self.content: str = content

        # ---- Temporal ----
        now = _now_ts()
        self.timestamp: str = timestamp or now
        self.last_accessed: str = last_accessed or now

        # ---- Semantic (mutable via evolution) ----
        self.context: Optional[str] = context
        self.keywords: List[str] = keywords or []
        self.tags: List[str] = tags or []

        # ---- Vector representation ----
        self.embedding: Optional[List[float]] = embedding

        # ---- Relational structure ----
        # links: other_note_id -> metadata (type, strength, reason, etc.)
        self.links: Dict[str, Dict[str, Any]] = links or {}

        # ---- Usage & evolution ----
        self.retrieval_count: int = retrieval_count
        self.evolution_history: List[Dict[str, Any]] = evolution_history or []

    # ----------------------------
    # Access & usage updates
    # ----------------------------

    def mark_accessed(self) -> None:
        """Update access metadata when the note is retrieved."""
        self.retrieval_count += 1
        self.last_accessed = _now_ts()

    # ----------------------------
    # Linking operations
    # ----------------------------

    def add_link(
        self, other_note_id: str, metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """
        Add or update a link to another memory note.

        Args:
            other_note_id (str): ID of the related memory note.
            metadata (Optional[Dict]): Relationship metadata
                (e.g., {"type": "related", "strength": 0.8})
        """
        self.links[other_note_id] = metadata or {}

    def remove_link(self, other_note_id: str) -> None:
        """Remove a link to another memory note."""
        if other_note_id in self.links:
            del self.links[other_note_id]

    # ----------------------------
    # Evolution tracking
    # ----------------------------

    def record_evolution(self, action: str, details: Dict[str, Any]) -> None:
        """
        Record a semantic evolution event.

        Args:
            action (str):
                Type of evolution (e.g., "update_context", "merge_tags").
            details (Dict):
                Arbitrary metadata describing the change.
        """
        self.evolution_history.append(
            {
                "timestamp": _now_ts(),
                "action": action,
                "details": details,
            }
        )

    # ----------------------------
    # Serialization (persistence)
    # ----------------------------

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialize the MemoryNote to a dictionary.

        This method is used for persistence (DB / JSON).
        """
        return {
            "id": self.id,
            "content": self.content,
            "timestamp": self.timestamp,
            "last_accessed": self.last_accessed,
            "context": self.context,
            "keywords": self.keywords,
            "tags": self.tags,
            "embedding": self.embedding,
            "links": self.links,
            "retrieval_count": self.retrieval_count,
            "evolution_history": self.evolution_history,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "MemoryNote":
        """
        Reconstruct a MemoryNote from a dictionary.
        """
        return cls(
            content=data["content"],
            note_id=data.get("id"),
            timestamp=data.get("timestamp"),
            context=data.get("context"),
            keywords=data.get("keywords"),
            tags=data.get("tags"),
            embedding=data.get("embedding"),
            links=data.get("links"),
            retrieval_count=data.get("retrieval_count", 0),
            last_accessed=data.get("last_accessed"),
            evolution_history=data.get("evolution_history"),
        )

    # ----------------------------
    # Debug / display helpers
    # ----------------------------

    def __repr__(self) -> str:
        return (
            f"MemoryNote(id={self.id!r}, "
            f"tags={self.tags}, "
            f"retrievals={self.retrieval_count})"
        )
